name: Auto Rebase Branches on Dev Update

on:
  push:
    branches:
      - dev  # Triggers when you update dev

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Authenticate with PAT
        env:
          PAT: ${{ secrets.REBASE_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase all branches on dev
        env:
          PAT: ${{ secrets.REBASE_PAT }}
        run: |
          branches=$(git branch -r | grep 'origin/' | grep -v 'origin/dev' | grep -v 'origin/main' | sed 's|origin/||')

          git checkout dev
          git pull origin dev

          for branch in $branches; do
            echo "Rebasing branch: $branch"
            git checkout $branch
            git rebase dev
            git push origin $branch --force-with-lease
          done
